import type { IndustryConfig } from "./types";

export const dentalConfig: IndustryConfig = {
  slug: "dental",
  name: "Dental Practice",
  vendors: {
    business: [
      // Dental supply vendors
      "Henry Schein",
      "Patterson Dental",
      "Benco Dental",
      "Darby Dental",
      "Net32",
      "Ultradent",
      "Dentsply Sirona",
      "Dentsply",
      "3M Dental",
      "3M ESPE",
      "Hu-Friedy",
      "Ivoclar Vivadent",
      "Kerr Dental",
      "Septodont",
      "Crosstex",
      "Young Dental",
      "Brasseler",
      "Midwest Dental",
      "Miltex",
      "Coltene",
      "GC America",
      "Shofu Dental",
      "Premier Dental",
      "Orascoptic",
      "SciCan",
      "A-dec",
      "Pelton & Crane",
      // Dental lab vendors
      "Glidewell",
      "Burbank Dental Lab",
      "Artistic Dental Lab",
      "Bay Area Dental Lab",
      "Pacific Dental Lab",
      // Practice software
      "Dentrix",
      "Eaglesoft",
      "Open Dental",
      "Pearl",
      "Weave",
      "Curve Dental",
      "Dentally",
      "Apteryx",
      "XrayVision",
      "Dexis",
      "Carestream Dental",
      "Planmeca",
      "iDentalSoft",
      // Payroll processors
      "ADP",
      "Gusto",
      "Paychex",
      "QuickBooks Payroll",
      "Intuit Payroll",
    ],
    personal: [
      "Netflix",
      "Spotify",
      "Hulu",
      "Disney+",
      "HBO Max",
      "Apple TV",
      "Amazon Prime Video",
      "YouTube Premium",
      "Peacock",
      "Paramount+",
      "Peloton",
      "DoorDash",
      "Uber Eats",
      "Grubhub",
      "Postmates",
      "HelloFresh",
      "Blue Apron",
      "Starbucks",
    ],
    ambiguous: [
      "Amazon",
      "Walmart",
      "Target",
      "Costco",
      "Sam's Club",
      "Staples",
      "Office Depot",
      "Best Buy",
      "Apple Store",
    ],
    patterns: [
      "dental lab",
      "dental laboratory",
      "gym",
      "fitness",
      "meal kit",
      "streaming",
    ],
  },
  seasonality: [
    1.05, // Jan - benefit reset
    1.0,  // Feb
    1.02, // Mar
    1.0,  // Apr
    0.98, // May
    0.9,  // Jun - summer dip
    0.85, // Jul - summer low
    0.88, // Aug
    0.95, // Sep
    0.98, // Oct
    1.08, // Nov - year-end rush
    1.12, // Dec - insurance rush
  ],
  benchmarks: {
    overheadRatio: {
      healthy: 0.55,
      target: [0.55, 0.65],
      elevated: 0.75,
      critical: 0.75,
    },
  },
  accountMappings: {
    business: [
      "lab fees",
      "dental supplies",
      "payroll",
      "payroll expenses",
      "rent",
      "rent or lease",
      "utilities",
      "insurance",
      "professional fees",
      "professional",
      "continuing education",
      "education",
      "marketing",
      "advertising",
      "equipment",
      "equipment rental",
      "instruments",
      "services",
      "medical waste",
      "uniforms",
      "software",
    ],
    personal: [
      "entertainment",
      "fitness",
      "personal",
      "owner's draw",
      "owner's personal",
      "personal expenses",
    ],
    ambiguous: [
      "supplies",
      "office supplies",
      "food",
      "meals",
      "meals and entertainment",
      "subscriptions",
      "miscellaneous",
      "other expenses",
      "uncategorized",
      "office",
    ],
  },
  debtServicePatterns: [
    "loan payment",
    "note payable",
    "loan interest",
    "equipment loan",
    "practice loan",
    "mortgage",
    "line of credit",
  ],
  ownerDrawPatterns: [
    "owner's draw",
    "owner's personal",
    "distributions",
    "owner salary",
    "owner draw",
  ],
};
