import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { db } from "@/lib/db";
import { practices } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { calculateProfitability } from "@/lib/finance/profitability";
import { calculateFreeCashFlow } from "@/lib/finance/cash-flow";
import { calculateBudgetVsActual, getBudget } from "@/lib/finance/budget";

export async function generateMonthlyReport(
  practiceId: string,
  startDate: Date,
  endDate: Date
): Promise<Buffer> {
  // Fetch practice name
  const [practice] = await db
    .select({ name: practices.name })
    .from(practices)
    .where(eq(practices.id, practiceId))
    .limit(1);

  const practiceName = practice?.name || "Practice";

  // Fetch financial data
  const profitability = await calculateProfitability(practiceId, startDate, endDate);
  const cashFlow = await calculateFreeCashFlow(practiceId, 12);

  const year = endDate.getFullYear();
  const budget = await getBudget(practiceId, year);
  let budgetVsActual = null;
  if (budget) {
    budgetVsActual = await calculateBudgetVsActual(practiceId, year);
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(practiceName, 14, 22);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const periodStr = `${startDate.toLocaleDateString("en-US", { month: "long", year: "numeric" })} - ${endDate.toLocaleDateString("en-US", { month: "long", year: "numeric" })}`;
  doc.text(`Financial Report: ${periodStr}`, 14, 30);
  doc.text(`Generated by PracticePulse`, 14, 36);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-US")}`, pageWidth - 14, 36, { align: "right" });

  doc.setDrawColor(200);
  doc.line(14, 40, pageWidth - 14, 40);

  // --- Section 1: Key Metrics ---
  let y = 48;
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Key Metrics", 14, y);
  y += 4;

  const metrics = [
    ["Net Profit", formatMoney(profitability.trueNetProfit)],
    ["Overhead Ratio", `${(profitability.overheadRatio * 100).toFixed(1)}%`],
    ["Combined Free Cash", formatMoney(cashFlow.combined.freeCash)],
    ["Revenue (Period)", formatMoney(profitability.revenue.total)],
    ["Operating Expenses", formatMoney(profitability.operatingExpenses.total)],
    ["Owner Compensation", formatMoney(profitability.ownerCompensation)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: metrics,
    theme: "grid",
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
  });

  // --- Section 2: Profitability (Monthly Breakdown) ---
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Monthly Profitability", 14, y);
  y += 4;

  const profitRows = profitability.monthlyBreakdown.map((m) => [
    m.month,
    formatMoney(m.revenue),
    formatMoney(m.operatingExpenses),
    formatMoney(m.netOperatingIncome),
    `${(m.overheadRatio * 100).toFixed(1)}%`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Month", "Revenue", "Op. Expenses", "Net Income", "Overhead %"]],
    body: profitRows,
    theme: "grid",
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, halign: "right" },
    columnStyles: { 0: { halign: "left" } },
    margin: { left: 14, right: 14 },
  });

  // --- Section 3: Cash Flow Summary ---
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Cash Flow Summary", 14, y);
  y += 4;

  const cashRows = [
    ["Business Net Operating Income", formatMoney(cashFlow.business.netOperatingIncome)],
    ["Business Debt Service", formatMoney(cashFlow.business.debtService)],
    ["Business Free Cash", formatMoney(cashFlow.business.freeCash)],
    ["Personal Income (Draws)", formatMoney(cashFlow.personal.income)],
    ["Personal Expenses", formatMoney(cashFlow.personal.expenses)],
    ["Personal Free Cash", formatMoney(cashFlow.personal.freeCash)],
    ["Combined Free Cash", formatMoney(cashFlow.combined.freeCash)],
    ["3-Month Rolling Average", formatMoney(cashFlow.rollingAvg3mo)],
    ["12-Month Rolling Average", formatMoney(cashFlow.rollingAvg12mo)],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Item", "Amount"]],
    body: cashRows,
    theme: "grid",
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
  });

  // --- Section 4: Budget vs Actual (if exists) ---
  if (budgetVsActual && budgetVsActual.categories.length > 0) {
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;

    if (y > 220) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`Budget vs Actual (${year})`, 14, y);
    y += 4;

    const budgetRows = budgetVsActual.categories.map((cat) => [
      cat.accountRef,
      formatMoney(cat.monthlyTarget),
      formatMoney(cat.monthlyActual),
      formatMoney(cat.variance),
      `${cat.variancePercent.toFixed(1)}%`,
      cat.status,
    ]);

    budgetRows.push([
      "TOTAL",
      formatMoney(budgetVsActual.totalTarget),
      formatMoney(budgetVsActual.totalActual),
      formatMoney(budgetVsActual.totalVariance),
      "",
      "",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Category", "Target", "Actual", "Variance", "Var %", "Status"]],
      body: budgetRows,
      theme: "grid",
      headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, halign: "right" },
      columnStyles: { 0: { halign: "left" }, 5: { halign: "center" } },
      margin: { left: 14, right: 14 },
    });
  }

  // --- Footer ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      "Not financial advice. Consult your CPA/financial advisor.",
      14,
      doc.internal.pageSize.getHeight() - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" }
    );
  }

  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}

function formatMoney(value: number): string {
  const formatted = Math.abs(value).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return value < 0 ? `-$${formatted}` : `$${formatted}`;
}
